<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\TenderArchive;
use Illuminate\Support\Facades\DB;

class TenderArchiveSeeder extends Seeder
{
    public function run(): void
    {
        // Kosongkan tabel dulu agar tidak duplikat
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        TenderArchive::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $archives = [
            // ==================== RAK 1 & 2 (LEMARI KAYU DEPAN 1) ====================
            [
                'document_name'   => 'Document Bid',
                'title'           => 'Internal Vessel Replacement for Non UOP Items',
                'tender_ref_no'   => '2A07-TPE-CON-000-RFP-013',
                'client_name'     => 'PT Trans-Pacific Petrochemical Indotama (PT TPPI)',
                'vendor_name'     => 'PT Waskita Adhi Sejahtera',
                'location'        => 'Tuban / Surabaya',
                'year'            => 2023,
                'copy_info'       => 'Copy #1 of 7',
                'document_status' => 'Original',
                'cabinet_name'    => 'Lemari Kayu Depan',
                'rack_position'   => 'ATAS',
                'door_position'   => 'KIRI',
                'archive_code'    => 'LK-A-01',
                'notes'           => 'Sampul 1 - Dokumen Penawaran'
            ],
            [
                'document_name'   => 'Execution Bid',
                'title'           => 'TPPI REVAMP Project - Hand Over - Letter - Equipment Letter - Timesheet',
                'tender_ref_no'   => '-',
                'client_name'     => 'PT Trans-Pacific Petrochemical Indotama (PT TPPI)',
                'vendor_name'     => 'PT Waskita Adhi Sejahtera',
                'location'        => 'Tuban / Surabaya',
                'year'            => 2023,
                'copy_info'       => '# 01/01',
                'document_status' => 'Original',
                'cabinet_name'    => 'Lemari Kayu Depan',
                'rack_position'   => 'ATAS',
                'door_position'   => 'KANAN',
                'archive_code'    => 'LK-A-08',
                'notes'           => '-'
            ],
            [
                'document_name'   => 'Data Tender & Project',
                'title'           => 'Internal Vessel Replacement for 207-C-001R-AND-209-C-002R',
                'tender_ref_no'   => '2A07-TPE-CON-000-RFP-012',
                'client_name'     => 'PT Trans-Pacific Petrochemical Indotama (PT TPPI)',
                'vendor_name'     => 'PT Waskita Adhi Sejahtera',
                'location'        => 'Tuban / Surabaya',
                'year'            => 2023,
                'copy_info'       => 'Copy #1 of 1',
                'document_status' => 'Copy',
                'cabinet_name'    => 'Lemari Kayu Depan',
                'rack_position'   => 'ATAS',
                'door_position'   => 'KANAN',
                'archive_code'    => 'LK-A-09',
                'notes'           => '-'
            ],
            [
                'document_name'   => 'Document Bid',
                'title'           => 'Internal Vessel Replacement for Non UOP Items',
                'tender_ref_no'   => '2A07-TPE-CON-000-RFP-013',
                'client_name'     => 'PT Trans-Pacific Petrochemical Indotama (PT TPPI)',
                'vendor_name'     => 'PT Waskita Adhi Sejahtera',
                'location'        => 'Tuban / Surabaya',
                'year'            => 2023,
                'copy_info'       => 'Copy #2 of 7',
                'document_status' => 'Original',
                'cabinet_name'    => 'Lemari Kayu Depan',
                'rack_position'   => 'ATAS',
                'door_position'   => 'KIRI',
                'archive_code'    => 'LK-A-02',
                'notes'           => '-'
            ],
            [
                'document_name'   => 'Document Bid',
                'title'           => 'Internal Vessel Replacement for Non UOP Items',
                'tender_ref_no'   => '2A07-TPE-CON-000-RFP-013',
                'client_name'     => 'PT Trans-Pacific Petrochemical Indotama (PT TPPI)',
                'vendor_name'     => 'PT Waskita Adhi Sejahtera',
                'location'        => 'Tuban / Surabaya',
                'year'            => 2023,
                'copy_info'       => 'Copy #3 of 7',
                'document_status' => 'Original',
                'cabinet_name'    => 'Lemari Kayu Depan',
                'rack_position'   => 'ATAS',
                'door_position'   => 'KIRI',
                'archive_code'    => 'LK-A-03',
                'notes'           => '-'
            ],
            [
                'document_name'   => 'Document Bid',
                'title'           => 'Internal Vessel Replacement for Non UOP Items',
                'tender_ref_no'   => '2A07-TPE-CON-000-RFP-013',
                'client_name'     => 'PT Trans-Pacific Petrochemical Indotama (PT TPPI)',
                'vendor_name'     => 'PT Waskita Adhi Sejahtera',
                'location'        => 'Tuban / Surabaya',
                'year'            => 2023,
                'copy_info'       => 'Copy #4 of 7',
                'document_status' => 'Original',
                'cabinet_name'    => 'Lemari Kayu Depan',
                'rack_position'   => 'BAWAH',
                'door_position'   => 'KIRI',
                'archive_code'    => 'LK-B-04',
                'notes'           => '-'
            ],
            [
                'document_name'   => 'Document Bid',
                'title'           => 'Internal Vessel Replacement for Non UOP Items',
                'tender_ref_no'   => '2A07-TPE-CON-000-RFP-013',
                'client_name'     => 'PT Trans-Pacific Petrochemical Indotama (PT TPPI)',
                'vendor_name'     => 'PT Waskita Adhi Sejahtera',
                'location'        => 'Tuban / Surabaya',
                'year'            => 2023,
                'copy_info'       => 'Copy #5 of 8',
                'document_status' => 'Original',
                'cabinet_name'    => 'Lemari Kayu Depan',
                'rack_position'   => 'BAWAH',
                'door_position'   => 'KIRI',
                'archive_code'    => 'LK-B-05',
                'notes'           => '-'
            ],
            [
                'document_name'   => 'Document Bid',
                'title'           => 'Internal Vessel Replacement for Non UOP Items',
                'tender_ref_no'   => '2A07-TPE-CON-000-RFP-013',
                'client_name'     => 'PT Trans-Pacific Petrochemical Indotama (PT TPPI)',
                'vendor_name'     => 'PT Waskita Adhi Sejahtera',
                'location'        => 'Tuban / Surabaya',
                'year'            => 2023,
                'copy_info'       => 'Copy #6 of 9',
                'document_status' => 'Original',
                'cabinet_name'    => 'Lemari Kayu Depan',
                'rack_position'   => 'BAWAH',
                'door_position'   => 'KIRI',
                'archive_code'    => 'LK-B-06',
                'notes'           => '-'
            ],
            [
                'document_name'   => 'Document Bid',
                'title'           => 'Internal Vessel Replacement for Non UOP Items',
                'tender_ref_no'   => '2A07-TPE-CON-000-RFP-013',
                'client_name'     => 'PT Trans-Pacific Petrochemical Indotama (PT TPPI)',
                'vendor_name'     => 'PT Waskita Adhi Sejahtera',
                'location'        => 'Tuban / Surabaya',
                'year'            => 2023,
                'copy_info'       => 'Copy #7 of 10',
                'document_status' => 'Original',
                'cabinet_name'    => 'Lemari Kayu Depan',
                'rack_position'   => 'BAWAH',
                'door_position'   => 'KIRI',
                'archive_code'    => 'LK-B-07',
                'notes'           => '-'
            ],

            // ==================== RAK 3 (LEMARI KAYU DEPAN KE 3) ====================
            [
                'document_name'   => 'PQ Document',
                'title'           => 'Manpower Support Services (WELLS I)',
                'tender_ref_no'   => 'CS-78331',
                'client_name'     => 'Medco E&P Indonesia',
                'vendor_name'     => 'PT Waskita Adhi Sejahtera',
                'location'        => '-',
                'year'            => 2026,
                'copy_info'       => '1 of 1',
                'document_status' => 'Original',
                'cabinet_name'    => 'Lemari Kayu Depan ke 3',
                'rack_position'   => 'ATAS',
                'door_position'   => 'KANAN',
                'archive_code'    => 'LK3-A-KA-01',
                'notes'           => '-'
            ],
            [
                'document_name'   => 'Bid Document',
                'title'           => 'Manpower Support Services (WELLS I)',
                'tender_ref_no'   => 'CS-78331',
                'client_name'     => 'Medco E&P Indonesia',
                'vendor_name'     => 'PT Waskita Adhi Sejahtera',
                'location'        => '-',
                'year'            => 2026,
                'copy_info'       => '1 of 1',
                'document_status' => 'Original',
                'cabinet_name'    => 'Lemari Kayu Depan ke 3',
                'rack_position'   => 'ATAS',
                'door_position'   => 'KANAN',
                'archive_code'    => 'LK3-A-KA-02',
                'notes'           => '-'
            ],
            [
                'document_name'   => 'Sampul 1 - Admin & Teknis',
                'title'           => 'Skimming Catalyst NHT 202-R-001',
                'tender_ref_no'   => 'No-TDR20260931',
                'client_name'     => 'PT Trans-Pacific Petrochemical Indotama',
                'vendor_name'     => 'PT Waskita Adhi Sejahtera',
                'location'        => '-',
                'year'            => 2026,
                'copy_info'       => '1 of 1',
                'document_status' => 'Original',
                'cabinet_name'    => 'Lemari Kayu Depan ke 3',
                'rack_position'   => 'ATAS',
                'door_position'   => 'KANAN',
                'archive_code'    => 'LK3-A-KA-03',
                'notes'           => '-'
            ],
            [
                'document_name'   => 'Document PQ',
                'title'           => 'Mechanical Maintenance Services',
                'tender_ref_no'   => 'No. 4420004365',
                'client_name'     => 'BP Berau Ltd.',
                'vendor_name'     => 'PT Waskita Adhi Sejahtera',
                'location'        => '-',
                'year'            => 2026,
                'copy_info'       => '1 of 2',
                'document_status' => 'Original',
                'cabinet_name'    => 'Lemari Kayu Depan ke 3',
                'rack_position'   => 'BAWAH',
                'door_position'   => 'KIRI',
                'archive_code'    => 'LK3-B-KI-01',
                'notes'           => 'Jilid 1'
            ],
            [
                'document_name'   => 'Document PQ',
                'title'           => 'Mechanical Maintenance Services',
                'tender_ref_no'   => 'No. 4420004365',
                'client_name'     => 'BP Berau Ltd.',
                'vendor_name'     => 'PT Waskita Adhi Sejahtera',
                'location'        => '-',
                'year'            => 2026,
                'copy_info'       => '2 of 2',
                'document_status' => 'Original',
                'cabinet_name'    => 'Lemari Kayu Depan ke 3',
                'rack_position'   => 'BAWAH',
                'door_position'   => 'KIRI',
                'archive_code'    => 'LK3-B-KI-02',
                'notes'           => 'Jilid 2'
            ],
            [
                'document_name'   => 'Bid Document',
                'title'           => 'Internal Cleaning And Tube Thickness Check of Heat Exchanger During 2026 Turn Around (TA)',
                'tender_ref_no'   => 'PCJ - 3927 - CA',
                'client_name'     => 'PetroChina Internasional Jabung Ltd.',
                'vendor_name'     => 'PT Waskita Adhi Sejahtera',
                'location'        => '-',
                'year'            => 2026,
                'copy_info'       => '1 of 3',
                'document_status' => 'Original',
                'cabinet_name'    => 'Lemari Kayu Depan ke 3',
                'rack_position'   => 'ATAS',
                'door_position'   => 'KIRI',
                'archive_code'    => 'LK3-A-KI-01',
                'notes'           => 'Jilid 1'
            ],
            [
                'document_name'   => 'Bid Document',
                'title'           => 'Internal Cleaning And Tube Thickness Check of Heat Exchanger During 2026 Turn Around (TA)',
                'tender_ref_no'   => 'PCJ - 3927 - CA',
                'client_name'     => 'PetroChina Internasional Jabung Ltd.',
                'vendor_name'     => 'PT Waskita Adhi Sejahtera',
                'location'        => '-',
                'year'            => 2026,
                'copy_info'       => '2 of 3',
                'document_status' => 'Original',
                'cabinet_name'    => 'Lemari Kayu Depan ke 3',
                'rack_position'   => 'ATAS',
                'door_position'   => 'KIRI',
                'archive_code'    => 'LK3-A-KI-02',
                'notes'           => 'Jilid 2'
            ],
            [
                'document_name'   => 'Bid Document',
                'title'           => 'Internal Cleaning And Tube Thickness Check of Heat Exchanger During 2026 Turn Around (TA)',
                'tender_ref_no'   => 'PCJ - 3927 - CA',
                'client_name'     => 'PetroChina Internasional Jabung Ltd.',
                'vendor_name'     => 'PT Waskita Adhi Sejahtera',
                'location'        => '-',
                'year'            => 2026,
                'copy_info'       => '3 of 3',
                'document_status' => 'Original',
                'cabinet_name'    => 'Lemari Kayu Depan ke 3',
                'rack_position'   => 'ATAS',
                'door_position'   => 'KIRI',
                'archive_code'    => 'LK3-A-KI-03',
                'notes'           => 'Jilid 3'
            ],
            [
                'document_name'   => 'Bid Document - "C"',
                'title'           => 'Internal Cleaning And Tube Thickness Check of Heat Exchanger During 2026 Turn Around (TA)',
                'tender_ref_no'   => 'PCJ3927 - 202605CIVD - 14',
                'client_name'     => 'PetroChina Internasional Jabung Ltd.',
                'vendor_name'     => 'PT Waskita Adhi Sejahtera',
                'location'        => '-',
                'year'            => 2026,
                'copy_info'       => '1 of 1',
                'document_status' => 'Original',
                'cabinet_name'    => 'Lemari Kayu Depan ke 3',
                'rack_position'   => 'ATAS',
                'door_position'   => 'KIRI',
                'archive_code'    => 'LK3-A-KI-04',
                'notes'           => 'Dokumen C'
            ],

            // ==================== RAK 4 ====================
            [
                'document_name'   => 'Document PQ',
                'title'           => 'Catalyst Change Out Services',
                'tender_ref_no'   => 'No. 4420004012',
                'client_name'     => 'BP Berau Ltd.',
                'vendor_name'     => 'PT Waskita Adhi Sejahtera',
                'location'        => '-',
                'year'            => 2026,
                'copy_info'       => '1 of 2',
                'document_status' => 'Original',
                'cabinet_name'    => 'Lemari 4',
                'rack_position'   => 'ATAS',
                'door_position'   => 'KIRI',
                'archive_code'    => 'L4-A-01',
                'notes'           => 'Jilid 1'
            ],
            [
                'document_name'   => 'Document PQ',
                'title'           => 'Catalyst Change Out Services',
                'tender_ref_no'   => 'No. 4420004012',
                'client_name'     => 'BP Berau Ltd.',
                'vendor_name'     => 'PT Waskita Adhi Sejahtera',
                'location'        => '-',
                'year'            => 2026,
                'copy_info'       => '2 of 2',
                'document_status' => 'Original',
                'cabinet_name'    => 'Lemari 4',
                'rack_position'   => 'ATAS',
                'door_position'   => 'KIRI',
                'archive_code'    => 'L4-A-02',
                'notes'           => 'Jilid 2'
            ],
            [
                'document_name'   => 'Bid Document',
                'title'           => 'Utulize Isotank For DMDS AS SBC REPLACEMENT INSTALLATION FA-119',
                'tender_ref_no'   => 'ECR NO. 451-21-004 CMPEI PACKAGE',
                'client_name'     => 'Chandra Asri Petrochemical',
                'vendor_name'     => 'PT Waskita Adhi Sejahtera',
                'location'        => '-',
                'year'            => 2026,
                'copy_info'       => '1 of 1',
                'document_status' => 'Original',
                'cabinet_name'    => 'Lemari 4',
                'rack_position'   => 'ATAS',
                'door_position'   => 'KANAN',
                'archive_code'    => 'L4-A-03',
                'notes'           => '-'
            ],
            [
                'document_name'   => 'Doc. Pre-Qualification (PQ)',
                'title'           => 'Electrical Installation Maintenance Services',
                'tender_ref_no'   => 'CS66169',
                'client_name'     => 'Badan pengelola Migas Aceh (BPMA) Medco Energi Oil & Gas',
                'vendor_name'     => 'PT Waskita Adhi Sejahtera',
                'location'        => '-',
                'year'            => 2026,
                'copy_info'       => '1 of 1',
                'document_status' => 'Original',
                'cabinet_name'    => 'Lemari 4',
                'rack_position'   => 'BAWAH',
                'door_position'   => 'KIRI',
                'archive_code'    => 'L4-B-01',
                'notes'           => '-'
            ],
            [
                'document_name'   => 'Doc. Pre-Qualification (PQ)',
                'title'           => 'Pekerjaan Engineering Procurement Construction Installation dan Commisioning (EPCIC) di AS-15 Blok A Taban II',
                'tender_ref_no'   => 'CS58823',
                'client_name'     => 'Badan pengelola Migas Aceh (BPMA) Medco Energi Oil & Gas',
                'vendor_name'     => 'PT Waskita Adhi Sejahtera',
                'location'        => '-',
                'year'            => 2026,
                'copy_info'       => '1 of 1',
                'document_status' => 'Original',
                'cabinet_name'    => 'Lemari 4',
                'rack_position'   => 'BAWAH',
                'door_position'   => 'KANAN',
                'archive_code'    => 'L4-B-02',
                'notes'           => '-'
            ],

            // ==================== RAK 5 (LEMARI KAYU DEPAN KE 5) ====================
            [
                'document_name'   => 'PQ Document',
                'title'           => 'Jasa Persiapan Lokasi M-235',
                'tender_ref_no'   => 'SEBWPM-044/PLM-043/24-PL',
                'client_name'     => 'PT Pertamina EP & Samudra EnergyBWPMeruap',
                'vendor_name'     => 'PT Waskita Adhi Sejahtera',
                'location'        => '-',
                'year'            => 2024,
                'copy_info'       => '1 of 1',
                'document_status' => 'Copy',
                'cabinet_name'    => 'Lemari Kayu depan ke 5',
                'rack_position'   => 'ATAS',
                'door_position'   => 'KANAN',
                'archive_code'    => 'LK5-A-KA-01',
                'notes'           => '-'
            ],
            [
                'document_name'   => 'PQ Document',
                'title'           => 'KSO BATCH IV TAHUN 2025',
                'tender_ref_no'   => '-',
                'client_name'     => 'PT Pertamina EP & Samudra EnergyBWPMeruap',
                'vendor_name'     => 'PT Waskita Adhi Sejahtera',
                'location'        => '-',
                'year'            => 2025,
                'copy_info'       => '1 of 1',
                'document_status' => 'Original',
                'cabinet_name'    => 'Lemari Kayu depan ke 5',
                'rack_position'   => 'ATAS',
                'door_position'   => 'KANAN',
                'archive_code'    => 'LK5-A-KA-02',
                'notes'           => '-'
            ],
            [
                'document_name'   => 'Document PQ',
                'title'           => 'Long Term Site Project Modification At Tangguh LNG',
                'tender_ref_no'   => 'NO. 4420003973',
                'client_name'     => 'BP Berau Ltd. , Triagung Jaya Abadi',
                'vendor_name'     => 'PT Waskita Adhi Sejahtera',
                'location'        => '-',
                'year'            => 2025,
                'copy_info'       => '1 of 2',
                'document_status' => 'Original',
                'cabinet_name'    => 'Lemari Kayu depan ke 5',
                'rack_position'   => 'ATAS',
                'door_position'   => 'KANAN',
                'archive_code'    => 'LK5-A-KA-03',
                'notes'           => 'Jilid 1'
            ],
            [
                'document_name'   => 'Document PQ',
                'title'           => 'Long Term Site Project Modification At Tangguh LNG',
                'tender_ref_no'   => 'NO. 4420003973',
                'client_name'     => 'BP Berau Ltd. , Triagung Jaya Abadi',
                'vendor_name'     => 'PT Waskita Adhi Sejahtera',
                'location'        => '-',
                'year'            => 2025,
                'copy_info'       => '2 of 2',
                'document_status' => 'Original',
                'cabinet_name'    => 'Lemari Kayu depan ke 5',
                'rack_position'   => 'ATAS',
                'door_position'   => 'KANAN',
                'archive_code'    => 'LK5-A-KA-04',
                'notes'           => 'Jilid 2'
            ],
            [
                'document_name'   => 'Doc. Pre-Qualification (PQ)',
                'title'           => 'Storage Tank Cleaning Services',
                'tender_ref_no'   => 'CS69733',
                'client_name'     => 'Medco Energi Oil & Gas',
                'vendor_name'     => 'PT Waskita Adhi Sejahtera',
                'location'        => '-',
                'year'            => 2025,
                'copy_info'       => '1 of 1',
                'document_status' => 'Original',
                'cabinet_name'    => 'Lemari Kayu depan ke 5',
                'rack_position'   => 'ATAS',
                'door_position'   => 'KIRI',
                'archive_code'    => 'LK5-A-KI-01',
                'notes'           => '-'
            ],
            [
                'document_name'   => 'Bid Document',
                'title'           => 'Pekerjaan Jasa Blanket Konstruksi',
                'tender_ref_no'   => 'CS66828',
                'client_name'     => 'Medco Energi Oil & Gas',
                'vendor_name'     => 'PT Waskita Adhi Sejahtera',
                'location'        => '-',
                'year'            => 2025,
                'copy_info'       => '1 of 2',
                'document_status' => 'Original',
                'cabinet_name'    => 'Lemari Kayu depan ke 5',
                'rack_position'   => 'ATAS',
                'door_position'   => 'KIRI',
                'archive_code'    => 'LK5-A-KI-02',
                'notes'           => '-'
            ],
            [
                'document_name'   => 'PQ Document',
                'title'           => 'Pekerjaan Terintegrasi Pengerukan Sedimen Bendungan Tangga Buang Spoilbank',
                'tender_ref_no'   => '-',
                'client_name'     => 'Jasa Tirta I',
                'vendor_name'     => 'PT Waskita Adhi Sejahtera',
                'location'        => '-',
                'year'            => 2025,
                'copy_info'       => '1 of 1',
                'document_status' => 'Original',
                'cabinet_name'    => 'Lemari Kayu depan ke 5',
                'rack_position'   => 'ATAS',
                'door_position'   => 'KIRI',
                'archive_code'    => 'LK5-A-KI-03',
                'notes'           => '-'
            ],
            [
                'document_name'   => 'PQ Document',
                'title'           => 'Field Operation Assistance Services',
                'tender_ref_no'   => 'CS-69112',
                'client_name'     => 'Medco E&P Grissik, Ltd.',
                'vendor_name'     => 'PT Waskita Adhi Sejahtera',
                'location'        => '-',
                'year'            => 2025,
                'copy_info'       => '1 of 1',
                'document_status' => 'Original',
                'cabinet_name'    => 'Lemari Kayu depan ke 5',
                'rack_position'   => 'ATAS',
                'door_position'   => 'KIRI',
                'archive_code'    => 'LK5-A-KI-04',
                'notes'           => '-'
            ],
            [
                'document_name'   => 'Document PQ',
                'title'           => 'Pengadaan Jasa Penunjang Tenaga Kerja',
                'tender_ref_no'   => 'S25006BSD',
                'client_name'     => 'SSKMIGAS, Pertamina PHE Tomori, Medco Energi Oil & Gas',
                'vendor_name'     => 'PT Waskita Adhi Sejahtera',
                'location'        => '-',
                'year'            => 2025,
                'copy_info'       => '1 of 1',
                'document_status' => 'Original',
                'cabinet_name'    => 'Lemari Kayu depan ke 5',
                'rack_position'   => 'BAWAH',
                'door_position'   => 'KANAN',
                'archive_code'    => 'LK5-B-KA-01',
                'notes'           => '-'
            ],
            [
                'document_name'   => 'PQ Document',
                'title'           => 'Pengadaan Tenaga Kerja Jasa Penunjang',
                'tender_ref_no'   => 'No.SPHR01081A',
                'client_name'     => 'Pertamina Hulu Rokan',
                'vendor_name'     => 'PT Waskita Adhi Sejahtera',
                'location'        => '-',
                'year'            => 2025,
                'copy_info'       => '1 of 1',
                'document_status' => 'Original',
                'cabinet_name'    => 'Lemari Kayu depan ke 5',
                'rack_position'   => 'ATAS',
                'door_position'   => 'KANAN',
                'archive_code'    => 'LK5-A-KA-05',
                'notes'           => '-'
            ],
        ];

        foreach ($archives as $item) {
            TenderArchive::create($item);
        }
    }
}